# Generated by Django 4.0.4 on 2022-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default value', upload_to='pictures/'),
        ),
    ]
