# Generated by Django 4.0.4 on 2022-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographs', '0002_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default value', upload_to='images/'),
        ),
    ]
